version: "3"

services:
  postgres1:
    image: postgres
    ports:
      - 54321:5432
    environment:
      max_prepared_transactions: "10"
  postgres2:
    image: postgres
    ports:
      - 54322:5432
    environment:
      max_prepared_transactions: "10"
