name: Build and test
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build core
        run: yarn build
        working-directory: ./core
      - name: Test core
        run: yarn test
        working-directory: ./core
