name: Build and test
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install node v14
        run: nvm install 14
      - name: Show node version
        run: node --version