name: CI
on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: CI core
        run: VERSION=${{ matrix.node-version }} yarn build:version && yarn build:types && yarn lint && yarn test
        working-directory: ./core

      - name: CI server
        run: VERSION=${{ matrix.node-version }} yarn build:version && yarn build:types && yarn lint
        working-directory: ./server

      - name: CI crud
        run: VERSION=${{ matrix.node-version }} yarn build:version && yarn build:types && yarn lint && yarn test
        working-directory: ./crud

      - name: CI postgres
        run: VERSION=${{ matrix.node-version }} yarn build:version && yarn build:types && yarn lint
        working-directory: ./postgres

      - name: CI server-postgres
        run: VERSION=${{ matrix.node-version }} yarn build:version && yarn build:types && yarn lint
        working-directory: ./server-postgres

      - name: CI mariadb
        run: VERSION=${{ matrix.node-version }} yarn build:version && yarn build:types && yarn lint
        working-directory: ./mariadb

      - name: CI channels
        run: VERSION=${{ matrix.node-version }} yarn build:version && yarn build:types && yarn lint && yarn test
        working-directory: ./channels
